kind: Service
apiVersion: v1
metadata:
  name: mongodb
  namespace: bancodefi
spec:
    clusterIP: None
    ports:
    -   port: 27017
    selector:
        app: mongodb

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: mongodb-node
    namespace: bancodefi
spec:
  serviceName: mongodb
  selector:
    matchLabels:
        app: mongodb
  replicas: 1
  template:
    metadata:
        labels:
            app: mongodb
    spec:
        containers:
        -   name: mongodb-node
            image: mongo:3.6
            command: [ "/usr/bin/mongod", "--smallfiles", "--bind_ip_all" ]
            volumeMounts:
            -   mountPath: "/data/db"
                name: mongo-data
            ports:
            -   containerPort: 27017
       
        
  volumeClaimTemplates:
  - metadata:
        name: mongo-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---

apiVersion: apps/v1
kind: Deployment
metadata:
    name: banco-server
    namespace: bancodefi
    labels:
      app: banco-server

spec:
  selector:
    matchLabels:
        app: banco-server
  replicas: 1
  template:

    metadata:
        labels:
            app: banco-server
    spec:

        containers:
        -   name: banco-server
            image: newearthart/bancoserver:1.6

            env:
            -   name: mongo__connectionString
                value: "mongodb://mongodb?connect=direct"


---          

apiVersion: apps/v1
kind: Deployment
metadata:
    name: banco-frontend
    namespace: bancodefi
    labels:
      app: banco-frontend

spec:
  selector:
    matchLabels:
        app: banco-frontend
  replicas: 1
  template:

    metadata:
        labels:
            app: banco-frontend
    spec:

        containers:
        -   name: banco-frontend
            image: newearthart/bancofrontend:1.2


---

apiVersion: v1
kind: Service
metadata:
    name: banco-server
    namespace: bancodefi
spec:
    ports:
    -   name: http 
        port: 80
    selector:
        app: banco-server

---

apiVersion: v1
kind: Service
metadata:
    name: banco-frontend
    namespace: bancodefi
spec:
    ports:
    -   name: http 
        port: 3000
    selector:
        app: banco-frontend

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cb-bancodefi-ingress
  namespace: bancodefi
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
spec:
  tls:
    - hosts:
      - bancodefi.staging.newearthart.tech
      secretName: rinkeby-bancodefi-tls

  rules:
  - host: bancodefi.staging.newearthart.tech
    http:
      paths:
      - path: /
        backend:
          serviceName: banco-frontend 
          servicePort: 3000
      
      - path: /api
        backend:
          serviceName: banco-server 
          servicePort: 80

      