version: '2'

services:

  mongo:
    image: mongo:3.6
    entrypoint: [ "/usr/bin/mongod", "--smallfiles", "--bind_ip_all"]

  server:
    image: newearthart/bancoserver:1.1
    ports:
      - 5012:80

